"use client";

import React, { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "kn" | "hi" | "ta" | "te" | "ml" | "mr" | "bn" | "gu" | "pa";

interface LanguageInfo {
  code: Language;
  name: string;
  nativeName: string;
}

export const supportedLanguages: LanguageInfo[] = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം" },
  { code: "mr", name: "Marathi", nativeName: "मराठी" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
];

interface Translations {
  [key: string]: {
    [lang in Language]: string;
  };
}

export const translations: Translations = {
  appTitle: {
    en: "Nimma Yatri",
    kn: "ನಿಮ್ಮ ಯಾತ್ರಿ",
    hi: "निम्मा यात्री",
    ta: "நம்ம ஆட்டோ-பாட்",
    te: "నమ్మ ఆటో-బాట్",
    ml: "നമ്മ ഓട്ടോ-ബോട്ട്",
    mr: "नम्मा ऑटो-बॉट",
    bn: "নম্মা অটো-বট",
    gu: "નમ્મા ઓટો-બોટ",
    pa: "ਨੰਮਾ ਆਟੋ-ਬੋਟ",
  },
  tagline: {
    en: "Your Bengaluru Survival Tool",
    kn: "ನಿಮ್ಮ ಬೆಂಗಳೂರು ಸರ್ವೈವಲ್ ಟೂಲ್",
    hi: "आपका बेंगलुरु सर्वाइवल टूल",
    ta: "உங்கள் பெங்களூரு சர்வைவல் டூல்",
    te: "మీ బెంగళూరు సర్వైవల్ టూల్",
    ml: "നിങ്ങളുടെ ബെംഗളൂരു സർവൈവൽ ടൂൾ",
    mr: "तुमचे बेंगळुरू सर्व्हायव्हल टूल",
    bn: "আপনার বেঙ্গালুরু সার্ভাইভাল টুল",
    gu: "તમારું બેંગલુરુ સર્વાઇવલ ટૂલ",
    pa: "ਤੁਹਾਡਾ ਬੈਂਗਲੁਰੂ ਸਰਵਾਈਵਲ ਟੂਲ",
  },
  calculator: {
    en: "Fare Calculator",
    kn: "ದರ ಕ್ಯಾಲ್ಕುಲೇಟರ್",
    hi: "किराया कैलकुलेटर",
    ta: "கட்டண கால்குலேட்டர்",
    te: "ఛార్జీ కాలిక్యులేటర్",
    ml: "നിരക്ക് കാൽക്കുലേറ്റർ",
    mr: "भाडे कॅल्क्युलेटर",
    bn: "ভাড়া ক্যালকুলেটর",
    gu: "ભાડું કેલ્ક્યુલેટર",
    pa: "ਕਿਰਾਇਆ ਕੈਲਕੁਲੇਟਰ",
  },
  phrases: {
    en: "Kannada Phrases",
    kn: "ಕನ್ನಡ ಪದಗಳು",
    hi: "कन्नड़ वाक्यांश",
    ta: "கன்னட சொற்றொடர்கள்",
    te: "కన్నడ పదబంధాలు",
    ml: "കന്നഡ വാക്യങ്ങൾ",
    mr: "कन्नड वाक्ये",
    bn: "কন্নড় বাক্যাংশ",
    gu: "કન્નડ શબ્દસમૂહો",
    pa: "ਕੰਨੜ ਵਾਕਾਂਸ਼",
  },
  liveMode: {
    en: "Live Negotiation",
    kn: "ಲೈವ್ ನೆಗೋಷಿಯೇಷನ್",
    hi: "लाइव बातचीत",
    ta: "நேரடி பேச்சுவார்த்தை",
    te: "లైవ్ చర్చలు",
    ml: "ലൈവ് ചർച്ച",
    mr: "थेट वाटाघाटी",
    bn: "লাইভ আলোচনা",
    gu: "લાઇવ વાટાઘાટ",
    pa: "ਲਾਈਵ ਗੱਲਬਾਤ",
  },
  panicButton: {
    en: "Emergency",
    kn: "ತುರ್ತು",
    hi: "आपातकाल",
    ta: "அவசரநிலை",
    te: "అత్యవసరం",
    ml: "അടിയന്തരാവസ്ഥ",
    mr: "आणीबाणी",
    bn: "জরুরি",
    gu: "કટોકટી",
    pa: "ਐਮਰਜੈਂਸੀ",
  },
  from: {
    en: "From (Pickup Location)",
    kn: "ಎಲ್ಲಿಂದ (ಪಿಕಪ್)",
    hi: "कहाँ से (पिकअप)",
    ta: "எங்கிருந்து (பிக்அப்)",
    te: "ఎక్కడి నుండి (పికప్)",
    ml: "എവിടെ നിന്ന് (പിക്കപ്പ്)",
    mr: "कुठून (पिकअप)",
    bn: "কোথা থেকে (পিকআপ)",
    gu: "ક્યાંથી (પિકઅપ)",
    pa: "ਕਿੱਥੋਂ (ਪਿਕਅੱਪ)",
  },
  to: {
    en: "To (Drop Location)",
    kn: "ಎಲ್ಲಿಗೆ (ಡ್ರಾಪ್)",
    hi: "कहाँ तक (ड्रॉप)",
    ta: "எங்கே (டிராப்)",
    te: "ఎక్కడికి (డ్రాప్)",
    ml: "എവിടേക്ക് (ഡ്രോപ്പ്)",
    mr: "कुठे (ड्रॉप)",
    bn: "কোথায় (ড্রপ)",
    gu: "ક્યાં (ડ્રોપ)",
    pa: "ਕਿੱਥੇ (ਡ੍ਰੌਪ)",
  },
  calculateFare: {
    en: "Calculate Fare",
    kn: "ದರ ಲೆಕ್ಕ ಹಾಕಿ",
    hi: "किराया गणना करें",
    ta: "கட்டணம் கணக்கிடு",
    te: "ఛార్జీ లెక్కించు",
    ml: "നിരക്ക് കണക്കാക്കുക",
    mr: "भाडे मोजा",
    bn: "ভাড়া গণনা করুন",
    gu: "ભાડું ગણો",
    pa: "ਕਿਰਾਇਆ ਗਿਣੋ",
  },
  useCurrentLocation: {
    en: "Use Current Location",
    kn: "ಪ್ರಸ್ತುತ ಸ್ಥಳ ಬಳಸಿ",
    hi: "वर्तमान स्थान का उपयोग करें",
    ta: "தற்போதைய இருப்பிடத்தைப் பயன்படுத்து",
    te: "ప్రస్తుత స్థానాన్ని ఉపయోగించు",
    ml: "നിലവിലെ സ്ഥാനം ഉപയോഗിക്കുക",
    mr: "सध्याचे स्थान वापरा",
    bn: "বর্তমান অবস্থান ব্যবহার করুন",
    gu: "વર્તમાન સ્થાન વાપરો",
    pa: "ਮੌਜੂਦਾ ਟਿਕਾਣਾ ਵਰਤੋ",
  },
  wonAndHalf: {
    en: "Won-and-Half (1.5x)",
    kn: "ಒಂದೂವರೆ (1.5x)",
    hi: "डेढ़ गुना (1.5x)",
    ta: "ஒன்றரை (1.5x)",
    te: "ఒకటిన్నర (1.5x)",
    ml: "ഒന്നര (1.5x)",
    mr: "दीडपट (1.5x)",
    bn: "দেড় গুণ (1.5x)",
    gu: "દોઢ ગણું (1.5x)",
    pa: "ਡੇਢ ਗੁਣਾ (1.5x)",
  },
  rainSurge: {
    en: "Rain Surge (+30%)",
    kn: "ಮಳೆ ಸರ್ಜ್ (+30%)",
    hi: "बारिश सर्ज (+30%)",
    ta: "மழை சர்ஜ் (+30%)",
    te: "వర్షం సర్జ్ (+30%)",
    ml: "മഴ സർജ് (+30%)",
    mr: "पाऊस सर्ज (+30%)",
    bn: "বৃষ্টি সার্জ (+30%)",
    gu: "વરસાદ સર્જ (+30%)",
    pa: "ਮੀਂਹ ਸਰਜ (+30%)",
  },
  nightRate: {
    en: "Night (10PM-5AM)",
    kn: "ರಾತ್ರಿ (10PM-5AM)",
    hi: "रात (10PM-5AM)",
    ta: "இரவு (10PM-5AM)",
    te: "రాత్రి (10PM-5AM)",
    ml: "രാത്രി (10PM-5AM)",
    mr: "रात्र (10PM-5AM)",
    bn: "রাত (10PM-5AM)",
    gu: "રાત (10PM-5AM)",
    pa: "ਰਾਤ (10PM-5AM)",
  },
  distance: {
    en: "Distance",
    kn: "ದೂರ",
    hi: "दूरी",
    ta: "தூரம்",
    te: "దూరం",
    ml: "ദൂരം",
    mr: "अंतर",
    bn: "দূরত্ব",
    gu: "અંતર",
    pa: "ਦੂਰੀ",
  },
  fairPrice: {
    en: "Fair Price",
    kn: "ಸರಿಯಾದ ಬೆಲೆ",
    hi: "उचित मूल्य",
    ta: "நியாயமான விலை",
    te: "న్యాయమైన ధర",
    ml: "ന്യായമായ വില",
    mr: "योग्य किंमत",
    bn: "ন্যায্য মূল্য",
    gu: "યોગ્ય કિંમત",
    pa: "ਉਚਿਤ ਕੀਮਤ",
  },
  scamAlert: {
    en: "SCAM ALERT!",
    kn: "ಮೋಸ ಎಚ್ಚರಿಕೆ!",
    hi: "धोखाधड़ी चेतावनी!",
    ta: "மோசடி எச்சரிக்கை!",
    te: "మోసం హెచ్చరిక!",
    ml: "തട്ടിപ്പ് മുന്നറിയിപ്പ്!",
    mr: "फसवणूक इशारा!",
    bn: "প্রতারণা সতর্কতা!",
    gu: "છેતરપિંડી ચેતવણી!",
    pa: "ਧੋਖਾਧੜੀ ਚੇਤਾਵਨੀ!",
  },
  clickToPlay: {
    en: "Tap card to play audio",
    kn: "ಆಡಿಯೋ ಪ್ಲೇ ಮಾಡಲು ಕಾರ್ಡ್ ಟ್ಯಾಪ್ ಮಾಡಿ",
    hi: "ऑडियो चलाने के लिए कार्ड टैप करें",
    ta: "ஆடியோ இயக்க கார்டை தட்டவும்",
    te: "ఆడియో ప్లే చేయడానికి కార్డ్ ట్యాప్ చేయండి",
    ml: "ഓഡിയോ പ്ലേ ചെയ്യാൻ കാർഡ് ടാപ്പ് ചെയ്യുക",
    mr: "ऑडिओ प्ले करण्यासाठी कार्ड टॅप करा",
    bn: "অডিও চালাতে কার্ড ট্যাপ করুন",
    gu: "ઓડિયો ચલાવવા કાર્ડ ટેપ કરો",
    pa: "ਆਡੀਓ ਚਲਾਉਣ ਲਈ ਕਾਰਡ ਟੈਪ ਕਰੋ",
  },
  startLive: {
    en: "Start Live Negotiation",
    kn: "ಲೈವ್ ನೆಗೋಷಿಯೇಷನ್ ಪ್ರಾರಂಭಿಸಿ",
    hi: "लाइव बातचीत शुरू करें",
    ta: "நேரடி பேச்சுவார்த்தை தொடங்கு",
    te: "లైవ్ చర్చలు ప్రారంభించు",
    ml: "ലൈവ് ചർച്ച ആരംഭിക്കുക",
    mr: "थेट वाटाघाटी सुरू करा",
    bn: "লাইভ আলোচনা শুরু করুন",
    gu: "લાઇવ વાટાઘાટ શરૂ કરો",
    pa: "ਲਾਈਵ ਗੱਲਬਾਤ ਸ਼ੁਰੂ ਕਰੋ",
  },
  stopLive: {
    en: "Stop",
    kn: "ನಿಲ್ಲಿಸಿ",
    hi: "रोकें",
    ta: "நிறுத்து",
    te: "ఆపు",
    ml: "നിർത്തുക",
    mr: "थांबा",
    bn: "থামান",
    gu: "રોકો",
    pa: "ਰੋਕੋ",
  },
  listening: {
    en: "Listening...",
    kn: "ಕೇಳುತ್ತಿದೆ...",
    hi: "सुन रहा है...",
    ta: "கேட்கிறது...",
    te: "వింటోంది...",
    ml: "കേൾക്കുന്നു...",
    mr: "ऐकत आहे...",
    bn: "শুনছে...",
    gu: "સાંભળી રહ્યું છે...",
    pa: "ਸੁਣ ਰਿਹਾ ਹੈ...",
  },
  aiAdvice: {
    en: "AI Advice",
    kn: "AI ಸಲಹೆ",
    hi: "AI सलाह",
    ta: "AI ஆலோசனை",
    te: "AI సలహా",
    ml: "AI ഉപദേശം",
    mr: "AI सल्ला",
    bn: "AI পরামর্শ",
    gu: "AI સલાહ",
    pa: "AI ਸਲਾਹ",
  },
  fakeCall: {
    en: "Fake Police Call",
    kn: "ನಕಲಿ ಪೋಲೀಸ್ ಕಾಲ್",
    hi: "नकली पुलिस कॉल",
    ta: "போலி போலீஸ் அழைப்பு",
    te: "నకిలీ పోలీసు కాల్",
    ml: "വ്യാജ പോലീസ് കോൾ",
    mr: "बनावट पोलीस कॉल",
    bn: "নকল পুলিশ কল",
    gu: "નકલી પોલીસ કોલ",
    pa: "ਨਕਲੀ ਪੁਲਿਸ ਕਾਲ",
  },
  emergencyHelp: {
    en: "Emergency Helplines",
    kn: "ತುರ್ತು ಸಹಾಯವಾಣಿ",
    hi: "आपातकालीन हेल्पलाइन",
    ta: "அவசர உதவி எண்கள்",
    te: "అత్యవసర హెల్ప్‌లైన్లు",
    ml: "അടിയന്തര ഹെൽപ്പ്‌ലൈനുകൾ",
    mr: "आणीबाणी हेल्पलाइन",
    bn: "জরুরি হেল্পলাইন",
    gu: "કટોકટી હેલ્પલાઇન",
    pa: "ਐਮਰਜੈਂਸੀ ਹੈਲਪਲਾਈਨ",
  },
  connected: {
    en: "Connected",
    kn: "ಸಂಪರ್ಕಿತ",
    hi: "जुड़ा हुआ",
    ta: "இணைக்கப்பட்டது",
    te: "కనెక్ట్ అయింది",
    ml: "കണക്റ്റ് ചെയ്തു",
    mr: "जोडलेले",
    bn: "সংযুক্ত",
    gu: "જોડાયેલ",
    pa: "ਜੁੜਿਆ",
  },
  disconnected: {
    en: "Disconnected",
    kn: "ಸಂಪರ್ಕ ಕಡಿತ",
    hi: "डिस्कनेक्ट",
    ta: "துண்டிக்கப்பட்டது",
    te: "డిస్‌కనెక్ట్",
    ml: "വിച്ഛേദിച്ചു",
    mr: "डिस्कनेक्ट",
    bn: "সংযোগ বিচ্ছিন্ন",
    gu: "ડિસ્કનેક્ટ",
    pa: "ਡਿਸਕਨੈਕਟ",
  },
  loading: {
    en: "Loading...",
    kn: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    hi: "लोड हो रहा है...",
    ta: "ஏற்றுகிறது...",
    te: "లోడ్ అవుతోంది...",
    ml: "ലോഡ് ചെയ്യുന്നു...",
    mr: "लोड होत आहे...",
    bn: "লোড হচ্ছে...",
    gu: "લોડ થઈ રહ્યું છે...",
    pa: "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
  },
  areaIntel: {
    en: "Area Intel",
    kn: "ಪ್ರದೇಶ ಮಾಹಿತಿ",
    hi: "क्षेत्र जानकारी",
    ta: "பகுதி தகவல்",
    te: "ప్రాంత సమాచారం",
    ml: "ഏരിയ വിവരം",
    mr: "क्षेत्र माहिती",
    bn: "এলাকা তথ্য",
    gu: "વિસ્તાર માહિતી",
    pa: "ਖੇਤਰ ਜਾਣਕਾਰੀ",
  },
  proTips: {
    en: "Pro Tips from Locals",
    kn: "ಸ್ಥಳೀಯರಿಂದ ಪ್ರೊ ಟಿಪ್ಸ್",
    hi: "स्थानीय लोगों से प्रो टिप्स",
    ta: "உள்ளூர் மக்களிடமிருந்து ப்ரோ டிப்ஸ்",
    te: "స్థానికుల నుండి ప్రో టిప్స్",
    ml: "പ്രാദേശിക ആളുകളിൽ നിന്നുള്ള പ്രോ ടിപ്പുകൾ",
    mr: "स्थानिकांकडून प्रो टिप्स",
    bn: "স্থানীয়দের কাছ থেকে প্রো টিপস",
    gu: "સ્થાનિકો પાસેથી પ્રો ટિપ્સ",
    pa: "ਸਥਾਨਕ ਲੋਕਾਂ ਤੋਂ ਪ੍ਰੋ ਟਿਪਸ",
  },
  neverScammed: {
    en: "Never Get Scammed Again",
    kn: "ಮತ್ತೆ ಮೋಸ ಹೋಗಬೇಡಿ",
    hi: "फिर कभी धोखा न खाएं",
    ta: "மீண்டும் ஏமாற்றப்படாதீர்கள்",
    te: "మళ్ళీ మోసపోకండి",
    ml: "വീണ്ടും തട്ടിപ്പിന് ഇരയാകരുത്",
    mr: "पुन्हा फसवणूक होऊ देऊ नका",
    bn: "আর কখনো প্রতারিত হবেন না",
    gu: "ફરી ક્યારેય છેતરાશો નહીં",
    pa: "ਦੁਬਾਰਾ ਕਦੇ ਧੋਖਾ ਨਾ ਖਾਓ",
  },
  selectLanguage: {
    en: "Select Language",
    kn: "ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ",
    hi: "भाषा चुनें",
    ta: "மொழியைத் தேர்ந்தெடுக்கவும்",
    te: "భాషను ఎంచుకోండి",
    ml: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    mr: "भाषा निवडा",
    bn: "ভাষা নির্বাচন করুন",
    gu: "ભાષા પસંદ કરો",
    pa: "ਭਾਸ਼ਾ ਚੁਣੋ",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[key]?.[language] || translations[key]?.["en"] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
